database:
  # Disponivel:
  # Caso necessario, mude a configuracao do banco de dados no arquivo de respectivo nome.
  # Obs -> Por padrao, a imagem docker ja vem com o MariaDB instalado
  # - MariaDB (Recomendado)
  # - SQLite?
  # - FlatFile?
  type: MariaDB

config:
  # O famoso contador antes do teleporte
  teleport-countdown: 5
  # Tempo para poder teleportar novamente
  teleport-cooldown: 5

  teleport-cancel-on-move: true
  teleport-cancel-on-damage: true

  # Quantidade de homes que um jogador tem por padrao, caso nao tenha a permissao
  # homes.limit.number ou homes.limit.bypass
  homes-limit: 3

visual:
  particle:
    # Tipos:
    # - Circle
    #   - Particula -> Particle
    #   - Raio -> Int
    #   - Animate -> Boolean (Aparecer uma particula por vez)
    # - Image: Pixels pretos (valor rgb menos de 20 em todas as cores) serao transparentes
    #   - Path -> String
    #   - Largura -> Int
    #   - Altura -> Int
    #   - TamanhoParticula -> Float
    #   - DividirTamanho -> Float
    # - Video: Nao existe transparencia
    #   - Path -> String (De preferencia com final .banana)
    #     - Recomendado pre-computar o video utilizando "/homedebug particle video path width height size divide duration false")
    #       dentro do servidor, para gerar arquivo ".banana".
    #   - Largura -> Int
    #   - Altura -> Int
    #   - TamanhoParticula -> Float
    #   - DividirTamanho -> Float
    #   - Duracao -> Int
    #     - Zero para a duracao do video.
    teleport-start:
      - "IMAGE:plugins/Homes/rick.png:32:32:0.6:10"
      - "CIRCLE:FIREWORK:5:true"

  sound:
    teleport-start: entity.enderman.teleport
    teleport-end: block.end_portal_frame.fill
    teleport-cancel: block.fire.extinguish